# Generated by Django 5.1.3 on 2024-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='type_insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
