# Generated by Django 5.1.3 on 2024-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_information_type_insurance_alter_information_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='type_insurance',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('health', 'health')], max_length=100, null=True),
        ),
    ]
