# Generated by Django 5.1.3 on 2024-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0004_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(upload_to='partners'),
        ),
    ]
