# Generated by Django 5.1.3 on 2025-01-07 12:08

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0007_alter_information_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='content',
        ),
        migrations.RemoveField(
            model_name='information',
            name='hidden_info',
        ),
        migrations.RemoveField(
            model_name='information',
            name='title',
        ),
        migrations.CreateModel(
            name='InformationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(max_length=500)),
                ('hidden_info', models.TextField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web_pages.information')),
            ],
            options={
                'verbose_name': 'information Translation',
                'db_table': 'web_pages_information_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
