# Generated by Django 5.1.3 on 2025-03-26 16:47

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0008_remove_information_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='informationtranslation',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='informationtranslation',
            name='hidden_info',
            field=models.TextField(blank=True, null=True, verbose_name='Hidden information'),
        ),
        migrations.AlterField(
            model_name='information',
            name='type_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_type', to='web_pages.insurancetypes'),
        ),
        migrations.CreateModel(
            name='InsuranceTypesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('type_insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='web_pages.insurancetypes')),
            ],
            options={
                'verbose_name': 'insurance types Translation',
                'db_table': 'web_pages_insurancetypes_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
