# Generated by Django 5.1.3 on 2025-03-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0010_alter_insurancetypestranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetypestranslation',
            name='description',
            field=models.TextField(),
        ),
    ]
