# Generated by Django 5.1.3 on 2025-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0011_alter_insurancetypestranslation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationtranslation',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
