# Generated by Django 5.1.3 on 2024-12-03 10:59

import django.db.models.deletion
import health_assist.packages.path_creation
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_employeeprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_packages', to='accounts.insuredcompanies')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_under_packages', to='packages.packages')),
            ],
        ),
        migrations.CreateModel(
            name='UnderPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('limit', models.CharField(max_length=255)),
                ('coverage', models.TextField()),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_company', to='accounts.insuredcompanies')),
                ('documents_needed', models.ManyToManyField(related_name='documents', to='packages.documents')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_packages', to='packages.packages')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=health_assist.packages.path_creation.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='packages.documents')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('under_package', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='packages.underpackages')),
            ],
        ),
    ]
