# Generated by Django 5.1.3 on 2024-11-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypackages',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_under_packages', to='packages.packages'),
        ),
    ]
