# Generated by Django 5.1.3 on 2025-01-07 10:51

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursementclaims',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_claims_documents', to='packages.documents'),
        ),
        migrations.AlterField(
            model_name='reimbursementclaims',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reimbursementclaims',
            name='under_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_claims_packages', to='packages.underpackages'),
        ),
        migrations.AlterField(
            model_name='reimbursementclaims',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_claims_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
