# Generated by Django 5.1.3 on 2024-11-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_employeeprofile_user'),
        ('packages', '0002_alter_companypackages_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underpackages',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_company', to='accounts.insuredcompanies'),
        ),
        migrations.AlterField(
            model_name='underpackages',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under_packages', to='packages.packages'),
        ),
    ]
