# Generated by Django 5.1.3 on 2024-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_underpackages_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underpackages',
            name='documents_needed',
            field=models.ManyToManyField(to='packages.documents'),
        ),
    ]
