# Generated by Django 5.1.3 on 2025-12-09 09:50

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_remove_documents_type_document_remove_packages_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderPackageNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='underpackagestranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='underpackages',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='un_package_names', to='packages.underpackagenames'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnderPackageNamesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='packages.underpackagenames')),
            ],
            options={
                'verbose_name': 'under package names Translation',
                'db_table': 'packages_underpackagenames_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
