# Generated by Django 5.1.3 on 2024-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_underpackages_documents_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='underpackages',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
