# Generated by Django 5.1.3 on 2024-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_underpackages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underpackages',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
