# Generated by Django 5.1.3 on 2024-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_alter_underpackages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underpackages',
            name='documents_needed',
            field=models.ManyToManyField(related_name='documents', to='packages.documents'),
        ),
    ]
