# Generated by Django 5.1.3 on 2024-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_uc_id_number_hashed_employeeprofile_uc_id_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='uc_id_num',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hnfusermodel',
            name='uc_id_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
