# Generated by Django 5.1.3 on 2024-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_employeeprofile_uc_id_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredcompanies',
            name='insurance_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
