# Generated by Django 5.1.3 on 2024-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_employeeprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hnfusermodel',
            name='uc_id_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
