# Generated by Django 5.1.3 on 2026-03-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_populate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuredcompanies',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
    ]
